I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script
    scene street with flash
  File "game/script.rpy", line 28, in <module>
    scene street with flash
NameError: name 'flash' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 28, in script
    scene street with flash
  File "/usr/share/renpy/renpy/ast.py", line 1674, in execute
    paired = renpy.python.py_eval(self.paired)
  File "/usr/share/renpy/renpy/python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/usr/share/renpy/renpy/python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 28, in <module>
    scene street with flash
NameError: name 'flash' is not defined

Linux-6.5.13-7-MANJARO-x86_64-with-glibc2.38 x86_64
Ren'Py 8.2.0.0+unofficial
Відлуння минулого 
Sun Feb 18 00:48:32 2024
